name: Linting

# Build on every branch every push and pull request change.
on:
  pull_request:
  push:
    branches:
      - "**"

jobs:
  lint:
    name: Check project quality with `mllint`
    runs-on: ubuntu-20.04

    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Clone project
        uses: actions/checkout@v2

      - name: Install mllint
        run: pipenv install --dev mllint

      - name: Run `mllint`
        run: mllint -o mllint-report.md

      - name: Upload `mllint` report
        uses: actions/upload-artifact@v2
        with:
          name: mllint-report.md
          path: mllint-report.md
